name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    # trigger manually for tmate support on failure with "gh workflow run rust.yml"; abort with touch /continue
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      CACHE_BUSTER: 20211021-00
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/.crates*
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}-${{ env.CACHE_BUSTER }}
    - name: Cache build
      uses: actions/cache@v2
      with:
        path: |
          ./target
        key: ${{ runner.os }}-build-${{ hashFiles('Cargo.lock') }}-${{ env.CACHE_BUSTER }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && failure() }}
      timeout-minutes: 60
      with:
        limit-access-to-actor: true
